<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:tem="http://tempuri.org/" xmlns:web="http://schemas.datacontract.org/2004/07/WebService_POS_Extreme.POS_Extreme_BL">
<soapenv:Header/>
<soapenv:Body>
<tem:processPOSRequest>
<!--Optional:-->
<tem:objRequest>
<!--Optional:-->
<web:cellid>111</web:cellid>
<!--Optional:-->
<web:cmsisdn>255716402861</web:cmsisdn>
<!--Optional:-->
<web:conf></web:conf>
<!--Optional:-->
<web:dealerPassword>aboutwork</web:dealerPassword>
<!--Optional:-->
<web:dealerUserName>sameer</web:dealerUserName>
<!--Optional:-->
<web:language></web:language>
<!--Optional:-->
<web:menu></web:menu>
<!--Optional:-->
<web:msisdn>255716402861</web:msisdn>
<!--Optional:-->
<web:package>day_megabox</web:package>
<!--Optional:-->
<web:password>2580</web:password>
<!--Optional:-->
<web:submenu></web:submenu>
</tem:objRequest>
</tem:processPOSRequest>
</soapenv:Body>
</soapenv:Envelope>